apps/adopcion/urls.py
from django.conf.urls import url
from . import views
#from mascota.views import index  no me funciona porque lo hice la estructura como la doc.oficial
from adopcion.views import index_adopcion, SolicitudList, SolicitudCreate,SolicitudUpdate, SolicitudDelete
#from adopcion.views import index_adopcion, SolicitudList

"""
urlpatterns = [
	url(r'^$', views.index, name='index'),

]
"""
###trabajaremos con clases
urlpatterns = [
	url(r'^$', index_adopcion),
	url(r'^solicitud/listar$', SolicitudList.as_view() , name='solicitud_listar'),
	url(r'^solicitud/nueva$', SolicitudCreate.as_view() , name='solicitud_crear'),
	url(r'^solicitud/editar/(?P<pk>\d+)$', SolicitudUpdate.as_view() , name='solicitud_editar'),
	url(r'^solicitud/eliminar/(?P<pk>\d+)$', SolicitudDelete.as_view() , name='solicitud_eliminar'),
]

apps/mascota/urls.py
from django.conf.urls import url
from . import views
#from mascota.views import index  no me funciona porque lo hice la estructura como la doc.oficial
#from mascota.views import mascota_view ya lo uso con la linea 2
#from mascota.views import mascota_list ya lo uso con la linea 2
##añadi para importa la class MascotaList
from django.contrib.auth.decorators import login_required
#####con clases:
from mascota.views import MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
urlpatterns = [
	url(r'^$', views.index, name='index'),
	#url(r'^$', index), no me fuciono, en el video si.
	url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
	url(r'^listar$', login_required(MascotaList.as_view()), name='mascota_listar'),
	url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
]

#cuando se haga peticion al url ,como MascotaList es una clase se añade .as_view() para ejecutarse como vista
#####version anterior:
"""
urlpatterns = [
	url(r'^$', views.index, name='index'),
	#url(r'^$', index), no me fuciono, en el video si.
	url(r'^nuevo$', views.mascota_view, name='mascota_crear'),
	url(r'^listar$', views.mascota_list, name='mascota_listar'),
	url(r'^editar/(?P<id_mascota>BARRAINVERTIDAd+)/$', views.mascota_edit, name='mascota_editar'),
	url(r'^eliminar/(?P<id_mascota>BARRAINVERTIDAd+)/$', views.mascota_delete, name='mascota_eliminar'),
]
"""

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login
""" version sin modificacion disponible para user
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('mascota.urls', namespace='mascota')),
    url(r'^adopcion/', include('adopcion.urls', namespace='adopcion')),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^$', login, {'template_name':'index.html'}, name='login')
]
"""
# vista basada en funcion(es propia de django):
#url(r'^', login, {'template_name':'index.html'}, name='login')

##################################################################

####### Era para que el user modifique su pass:
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('mascota.urls', namespace='mascota')),
    url(r'^adopcion/', include('adopcion.urls', namespace='adopcion')),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]
"""
- luego de realizar el bloqueo para que los que no son usuarios no puedan ingresar
 a links solo para usuarios. al intentar entrar a uno de esos links me envia error 404 con 
 el link http://localhost:8000/accounts/login/?next=/mascota/listar
 Para que nos envie al login real añadimos accounts/login/ al url que tiene este archivo login(index.html)
-luego de ya poder navegar en el navbar, añadimos el logout_then_login(importacion) y el url logout aqui.
En base.html tambien y el link goout, asi como en refugio/setting.py
"""
################################################################

templates/base/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
	<meta charset="UTF-8">
	<title> {% block title %} Refugio {% endblock title %} </title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
	{% block header %}
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="#">CodigoFacilito</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNavDropdown">
		    <ul class="navbar-nav">
		      <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Mascotas
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
		          <a class="dropdown-item" href="{% url 'mascota:mascota_crear' %}">Registrar</a>
		          <a class="dropdown-item" href="{% url 'mascota:mascota_listar' %}">Listas</a>         
		        </div>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Adopciones
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
		          <a class="dropdown-item" href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a>
		          <a class="dropdown-item" href="{% url 'adopcion:solicitud_listar' %}">Listar Solicitudes</a>		          
		        </div>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="/">Código Facilito</a>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Opciones
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
		          <a class="dropdown-item" href="{% url 'logout'  %}">Salir</a>		          
		        </div>
		      </li>
		    </ul>
		  </div>
		</nav>
	{% endblock header %}
	{% block content %}
		<h5>Este es el contenido del archivo base</h5>
	{% endblock content %}
	{% block footer %}
		<h5>Este es el footer del archivo base</h5>
	{% endblock footer %}
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>
<!--{#% url 'logout'  %#}-->