apps/mascota/urls.py
from django.conf.urls import url
from . import views
#from mascota.views import index  no me funciona porque lo hice la estructura como la doc.oficial
#from mascota.views import mascota_view ya lo uso con la linea 2
#from mascota.views import mascota_list ya lo uso con la linea 2
##añadi para importa la class MascotaList
from django.contrib.auth.decorators import login_required
#####con clases:
from mascota.views import MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
urlpatterns = [
	url(r'^$', views.index, name='index'),
	#url(r'^$', index), no me fuciono, en el video si.
	url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
	url(r'^listar$', login_required(MascotaList.as_view()), name='mascota_listar'),
	url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
]

#cuando se haga peticion al url ,como MascotaList es una clase se añade .as_view() para ejecutarse como vista
#####version anterior:
"""
urlpatterns = [
	url(r'^$', views.index, name='index'),
	#url(r'^$', index), no me fuciono, en el video si.
	url(r'^nuevo$', views.mascota_view, name='mascota_crear'),
	url(r'^listar$', views.mascota_list, name='mascota_listar'),
	url(r'^editar/(?P<id_mascota>BARRAINVERTIDAd+)/$', views.mascota_edit, name='mascota_editar'),
	url(r'^eliminar/(?P<id_mascota>BARRAINVERTIDAd+)/$', views.mascota_delete, name='mascota_eliminar'),
]
"""

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login
""" version sin modificacion disponible para user
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('mascota.urls', namespace='mascota')),
    url(r'^adopcion/', include('adopcion.urls', namespace='adopcion')),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^$', login, {'template_name':'index.html'}, name='login')
]
"""
# vista basada en funcion(es propia de django):
#url(r'^', login, {'template_name':'index.html'}, name='login')

##################################################################

####### Era para que el user modifique su pass:
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('mascota.urls', namespace='mascota')),
    url(r'^adopcion/', include('adopcion.urls', namespace='adopcion')),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]
"""
- luego de realizar el bloqueo para que los que no son usuarios no puedan ingresar
 a links solo para usuarios. al intentar entrar a uno de esos links me envia error 404 con 
 el link http://localhost:8000/accounts/login/?next=/mascota/listar
 Para que nos envie al login real añadimos accounts/login/ al url que tiene este archivo login(index.html)
-luego de ya poder navegar en el navbar, añadimos el logout_then_login(importacion) y el url logout aqui.
En base.html tambien y el link goout, asi como en refugio/setting.py
"""
################################################################

apps/mascota/models.py
from django.db import models
from  adopcion.models import Persona
# Create your models here.

class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)
	def __str__(self):
		return self.nombre
	
class Mascota(models.Model):
	nombre = models.CharField(max_length=50)
	sexo = models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rescate = models.DateField()
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	vacuna = models.ManyToManyField(Vacuna, blank=True)
	def __str__(self):
		return self.nombre

apps/mascota/forms.py
from django import forms
from  mascota.models import Mascota

class MascotaForm(forms.ModelForm):
	class Meta:
		model = Mascota
		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rescate',
			'persona',
			'vacuna',
		]
		labels = {
			'nombre': 'Nombre',
			'sexo': 'Sexo',
			'edad_aproximada' : 'Edad aproximada',
			'fecha_rescate' : 'Fecha de rescate',
			'persona' : 'Adoptante',
			'vacuna' : 'Vacuna',
		}
		widget = {
			'nombre' : forms.TextInput(attrs={'class':'form-control'}),
			'sexo' : forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada' : forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rescate' : forms.TextInput(attrs={'class':'form-control'}),
			'persona' : forms.Select(attrs={'class':'form-control'}),
			'vacuna' : forms.CheckboxSelectMultiple(),		
		} 
		

apps/mascota/views.py
from django.shortcuts import render, redirect
from mascota.forms import MascotaForm
from mascota.models import Mascota
#from django.http import HttpResponse
# Create your views here.
#estamos trabajando en vistas basadas en funciones, con clases es menos codigo
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

#vistas por funciones:
def index(request):
	return render(request,"mascota/index.html")
	#return HttpResponse("texto index para mascota")


def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	else:
		form = MascotaForm()
	return render(request, 'mascota/mascota_form.html', {'form':form})			

def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id')
	contexto = {'mascotas':mascota}
	return render(request, 'mascota/mascota_list.html', contexto)

def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_form.html', {'form':form})	

def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})				

###### vistas por clases
class MascotaList(ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'

class MascotaCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')
#success_url = reverse_lazy('mascota:mascota_listar') para enviarme a la lista de mascotas	

class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')
# vemos que en mascota_edit() le pasabamos el id, ahora ese id en MascotaUpdate estara como pk en urls.py	

class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')
	

templates/mascota/index.html
{% extends "base/base.html" %}
{% block title %}
	App Mascota
{% endblock title %}
{% block content %}
	<h6>Soy el contenido de app Mascota</h6>
{% endblock content %}

templates/mascota/mascota_delete.html
{% extends "base/base.html" %}
{% block content %}
	<form method="post">
		{% csrf_token %}		
		<h3>Desea eliminar el registro de {{ object.nombre }}?</h3>
		<button class="btn btn-danger" type="submit">Si, eliminar</button>
		<a class="btn btn-default" href=" {% url 'mascota:mascota_listar' %} ">Cancelar</a>
	</form>
{% endblock content %}

templates/mascota/mascota_form.html
{% extends "base/base.html" %}
{% block content %}
	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit">Guardar</button>
	</form>
{% endblock content %}

templates/mascota/mascota_list.html
{% extends "base/base.html" %}
{% block content %}
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Nombre</th>
	      <th scope="col">Sexo</th>
	      <th scope="col">Edad</th>
	      <th scope="col">Fecha de Rescate</th>
	      <th scope="col">Adoptante</th>
	      <th scope="col">Acciones</th>
	    </tr>
	  </thead>
	  <tbody>
	  	{# % if mascotas % #}
	  		{#% for mascota in mascotas  %#}
	  	{% if object_list %}
	  		{% for mascota in object_list  %}	
	  			<tr>	      
			      <td> {{mascota.id}} </td>
			      <td> {{mascota.nombre}} </td>
			      <td> {{mascota.sexo}} </td>
			      <td> {{mascota.edad_aproximada}} </td>
			      <td> {{mascota.fecha_rescate}} </td>
			      <td> {{mascota.persona.nombre}} {{mascota.persona.apellidos}} </td>
			      <td>
					<a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
					<a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>	
			      </td>
			    </tr>
	  		{% endfor %}
	  	{% else %}
	  		<h1>No hay registros de Mascotas</h1>	
	  	{% endif %}	    	    
	  </tbody>
	</table>
{% endblock content %}